<option value="12c">12 (Commerce)</option>
<option value="12b">12 (Biology)</option>
<option value="12s">12 (Computer Science)</option>
<option value="11c">11 (Commerce)</option>
<option value="11b">11 (Biology)</option>
<option value="11s">11 (Computer Science)</option>
<option value="10">10</option>
<option value="9">9</option>
<option value="8">8</option>
<option value="7">7</option>
<option value="6">6</option>
<option value="5">5</option>
<option value="4">4</option>
<option value="3">3</option>
<option value="2">2</option>
<option value="1">1</option>
<option value="pg">Pre-Nursery</option>
<option value="lkg">Nursery</option>
<option value="ukg">BV</option>